#!/bin/bash

BLOC_VERSION="1.0.0"
HOSTS="/etc/hosts"
RESOLVED="127.0.0.1"

if [ $# -eq 1 ]
then
    case "$1" in
        "-v"|"--version")
            echo "v$BLOC_VERSION"
            exit 0
            ;;
        "-h"|"--help")
            ;;
        *)
            DOMAIN=$1
            LINE="$RESOLVED $DOMAIN"
            echo $LINE >> $HOSTS
            exit 0
            ;;
    esac
elif [ $# -eq 2 ]
then
    case "$1" in
        "-u"|"--unblock")
            DOMAIN=$2
            sed -i '' -E "/^$RESOLVED $DOMAIN$/d" $HOSTS
            ;;
        *)
            ;;
    esac
    exit 0
fi

cat <<- EOF
Usage:
    bloc [OPT] ARGS
OPT:
    -u|--unblock
    -h|--help
    -v|--version
ARGS:
    sub.domain.tld (e.g. twitter.com, or www.facebook.com)
Examples:
    $ $0 twitter.com        # blocks twitter.com
    $ $0 -u twitter.com     # unblocks twitter.com
EOF
